### ISSUE TITLE
any plans to support https?

### ISSUE THREAD

**Issue by hugoledoux** [opengeogroep/openbasiskaart#39]
we moved our website to https and can't use your nice map anymore it seems.

any plans in the future? would be great.

**Comment by mtoonen** [comment]
Thanks for reporting :+1: 
I've asked if we could buy a certificate. Will get back to you.

**Comment by hugoledoux** [comment]
my colleague @kenohori used that free one from China:

https://buy.wosign.com/free/

and followed that tutorial: 
https://www.linode.com/docs/websites/nginx/startssl-wth-latest-nginx-debian-7

Our group website: https://3d.bk.tudelft.nl is now secure, since yesterday. So far so good

**Comment by matthijsln** [comment]
added certificate

**Comment by hugoledoux** [comment]
fantastic, many thanks!
