### ISSUE TITLE
Zwembad Zuiderpark niet zichtbaar

### ISSUE THREAD

**Issue by matthijsln** [opengeogroep/openbasiskaart#41]
Zie locatie POLYGON ((79350 451982, 79350 452520, 80014 452520, 80014 451982, 79350 451982))

In de tabel osm_new_buildings zit het gebouw voor het zwembad Zuiderpark niet, dus die wordt niet in de buildings* layers gerenderd.

Of het gebouw is heel recent of het wordt door de imposm configuratie niet geimporteerd.

In de openstreetmap visualisatie is het zwembad wel te zien, wel met een andere kleur dan andere panden:

![image001](https://cloud.githubusercontent.com/assets/1926261/10606016/10f967fa-7730-11e5-8ff5-f7548d9e54fd.png)

**Comment by matthijsln** [comment]
Huidig beeld:
![image](https://cloud.githubusercontent.com/assets/1926261/10606055/698122aa-7730-11e5-8606-59b5205dfda9.png)

**Comment by mtoonen** [comment]
Groenhovenbad doet het wel, heeft tag  <tag k="building" v="yes"/>, zuiderpark niet:

  <tag k="amenity" v="swimming_pool"/>
  <tag k="covered" v="yes"/>
  <tag k="leisure" v="swimming_pool"/>
  <tag k="name" v="Recreatiecentrum/Zwembad Zuiderpark"/>
  <tag k="ref:bag" v="518100000207021"/>
  <tag k="source" v="BAG"/>
  <tag k="source:date" v="2014-02-11"/>
  <tag k="sport" v="swimming"/>
  <tag k="start_date" v="2003"/>
